# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ArmaTDMarkovLoop <- function(m_TR, a_P) {
    .Call(`_darkpeak_ArmaTDMarkovLoop`, m_TR, a_P)
}

timesFour <- function(x) {
    .Call(`_darkpeak_timesFour`, x)
}

